groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: 'critical'
    annotations:
      summary: "Instance  is down"
      description: " of job  has been down for more than 2 minutes."